### ISSUE TITLE
Objects in JavaScript

### ISSUE THREAD

**Issue by umairayub79** [avsingh999/JavaScript-for-Developer#25]
I'd like to add objects in JavaScript example

**Comment by avsingh999** [comment]
Hi @umairayub79 Please Go Ahead. 😄

**Comment by avsingh999** [comment]
And don't forget to add this filename in Readme

**Comment by umairayub79** [comment]
@avsingh999 sure, I'll send the PR in few a hours ☺️

**Comment by umairayub79** [comment]
@avsingh999 PR sent check #37

**Comment by umairayub79** [comment]
@avsingh999 you have to label the PRs too
