### ISSUE TITLE
Request to add "hacktoberfest" topic to the repository.

### ISSUE THREAD

**Issue by smitpatel24** [avsingh999/JavaScript-for-Developer#39]
This is what Hacktoberfest website showed me when I created a pull request in a repository similar to this repo. I think we might face the same issue while creating a pull request for hacktoberfest :

Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR. 

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by umairayub79** [comment]
Yeah I got the same warning on PR in this repo.

**Comment by anupamabauri** [comment]
Yes, me too.

**Comment by anupamabauri** [comment]
The "hacktoberfest" topic should be added to this repository. Otherwise our PRs which are merged are treated as ineligible.

**Comment by avsingh999** [comment]
@smitpatel24 I have added this. 

Thanks for the open issue for this :smile:

**Comment by avsingh999** [comment]
@smitpatel24  If you or anyone wanted to open more issue they can I will add a label to those issues ❤️
