### ISSUE TITLE
While loop in Java Script

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/JavaScript-for-Developer#6]
Please ad .md file ❤️

**Comment by vedanttttt** [comment]
Please assign this to me

**Comment by sahajkedia** [comment]
@avsingh999  Can you assign this to me?
Thanks in Advance.  :smile:

**Comment by AmitManna99** [comment]
Please assign it to me

**Comment by nathzz30** [comment]
Can you Assign to me?  Thank you!
