### ISSUE TITLE
assignment operations in Java Script

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/JavaScript-for-Developer#8]

**Comment by jsgiant** [comment]
@avsingh999  I will do this. Can I?

**Comment by deepankkartikey** [comment]
@avsingh999 
A pull request is created for this: https://github.com/avsingh999/JavaScript-for-Developer/pull/18

**Comment by akshitkumar450** [comment]
please assign to me..i will work on this issue

**Comment by deepankkartikey** [comment]
@avsingh999 
I have updated the PR: https://github.com/avsingh999/JavaScript-for-Developer/pull/18
